# encode:utf8
version: 1
formatters:
  simple:
    format: '[%(levelname)s] [%(asctime)s %(filename)s:%(funcName)s]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  console_err:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: "log/event_log.log"
    mode: a
    # 单位为byte 1048576byte = 1M
    maxBytes: 1048576
    backupCount: 3
loggers:
  mylogger:
    level: DEBUG
    handlers: [console,console_err,file_handler]
    propagate: no
disable_existing_loggers: false
